Working version

diff --git a/libexec/terra/terra-join b/libexec/terra/terra-join
--- a/libexec/terra/terra-join
+++ b/libexec/terra/terra-join
@@ -7,9 +7,17 @@ set -e
 [[ $1 ]] || terra --bad-usage "$0"
 
 address=$(seth --to-address "$1")
+now=$(date +%s)
 
-key=$(curl -sS -d "address=$address" -X POST "https://dai-service.makerdao.com/token")
+export ETH_RPC_URL=https://mainnet.infura.io
+hash=$(seth keccak "$now")
+echo >&2 "Sending hashed message"
+sig=$(ethsign msg --from "$ETH_FROM" --data "$hash" --passphrase-file "$ETH_PASSWORD")
 
-[[ ${#key} = 27 ]] || { echo "Something went wrong. Could not get API key."; exit 1; }
+# key=$(curl -sS -d "address=$address&now=$now&sig=$sig" -X POST "https://dai-service.makerdao.com/token")
+key=$(curl -sS -d "address=$address&now=$now&sig=$sig" -X POST "http://localhost:3000/token")
 
+[[ ${#key} = 27 ]] || { echo >&2 "Something went wrong. Could not get API key."; exit 1; }
+
+echo >&2 "Verified."
 echo "$key"
